export const GET_DATA_PENDING = "GET_DATA_PENDING";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILED = "GET_DATA_FAILED";

export const INCREASE_PAGE_NUMBER = "INCREASE_PAGE_NUMBER";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
